//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAlumno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores_Curso
    {
        public int idCurso { get; set; }
        public string idProfesor { get; set; }
        public int Horas { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
